---
server:
  host: 0.0.0.0
  port: 7441
  apiToken: ""
schedule: "0 */6 * * *" # every 6th hour
clients:
  autobrr:
    host: http://localhost:7474
    apikey: API_KEY
  radarr:
    - name: radarr
      host: http://localhost:7878
      apikey: API_KEY
      filters:
        - 15
    - name: radarr4k
      host: http://localhost:7878
      apikey: API_KEY
      filters:
        - 16
  sonarr:
    - name: sonarr
      host: http://localhost:8989
      apikey: API_KEY
      filters:
        - 14
