---
server:
  host: 0.0.0.0
  port: 7441
  apiToken: ""
schedule: "0 */6 * * *" # every 6th hour
clients:
  autobrr:
    host: http://localhost:7474
    apikey: API_KEY
  arr:
    - name: radarr
      type: radarr
      host: http://localhost:7878
      apikey: API_KEY
      filters:
        - 15
      #matchRelease: false / true

    - name: radarr4k
      type: radarr
      host: http://localhost:7878
      apikey: API_KEY
      filters:
        - 16
      #matchRelease: false / true

    - name: sonarr
      type: sonarr
      host: http://localhost:8989
      apikey: API_KEY
      filters:
        - 14
      tagsInclude:
        - mytag
      tagsExclude:
        - myothertag
      #matchRelease: false / true

    - name: lidarr
      type: lidarr
      host: http://localhost:8686
      apikey: API_KEY
      filters:
        - 13
      #matchRelease: false / true

    - name: readarr
      type: readarr
      host: http://localhost:8787
      apikey: API_KEY
      filters:
        - 12
      #matchRelease: false # will not use other fields yet, so not needed.

    - name: whisparr
      type: whisparr
      host: http://localhost:6969
      apikey: API_KEY
      filters:
        - 69
      #matchRelease: false / true